networks:
  laranet: {}
services:
  pma:
    environment:
      PMA_HOST: database
    image: phpmyadmin/phpmyadmin
    networks:
      laranet: null
    ports:
    - published: 8080
      target: 80
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      DB_HOST: database
      DB_PORT: '3306'
    networks:
      laranet: null
    ports:
      - "80:80"
    volumes:
    - ./storage/www:/var/www
  database:
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_USER: laravel
    image: mariadb:10.4-bionic
    networks:
      laranet: null
    ports:
    - published: 3306
      target: 3306
    volumes:
    - ./storage/db:/var/lib/mysql
  queue:
    image: redis:5-alpine
    networks:
      laranet: null
    ports:
    - published: 6379
      target: 6379

version: '3.7'
